/*
En un lavadero de vehículos se relacionan al final del día la cantidad de taxis que se lavaron, la cantidad de buses, la cantidad de particulares y la cantidad de motos.
Se desea un programa que muestre el dinero realizado por cada tipo de vehículo (taxis, buses, particulares y motos) y el total realizado en el lavadero. El precio de lavado de los taxis es
de $3.000, el de los buses a $10.000, de los particulares $5.000 y de las motos a $2.000.
 */

//WORK-FLOW FUNCTION'S
function print(text) {
    document.write(text);
    document.write("</br>");
}

function lineBreak() {
    document.write("</br>");
    document.write("</br>");
}

function calculateEarningsPerWash(ammountOfWashedVehicles, washingPrice) {
    return (ammountOfWashedVehicles * washingPrice);
}

//Washing Prices
const taxiWashingCost = 3000;
const busWashingCost = 10000;
const particularWashingCost = 5000;
const bikeWashingCost = 2000;

//Ammount of washed vehicles per type
let ammountOfWashedTaxis = parseInt(prompt(`Ingrese la cantidad de TAXIS lavados el dia de hoy`));
let ammountOfWashedBuses = parseInt(prompt(`Ingrese la cantidad de BUSES lavados el dia de hoy`));
let ammountOfWashedBikes = parseInt(prompt(`Ingrese la cantidad de MOTOS lavadas el dia de hoy`));
let ammountOfWashedParticular = parseInt(prompt(`Ingrese la cantidad de PARTICULARES lavadas el dia de hoy`));
let totalVehiclesWashed = (ammountOfWashedTaxis + ammountOfWashedBuses + ammountOfWashedBikes + ammountOfWashedParticular);

// //Money Generated by each type of vehicle
let moneyGeneratedByTaxiWashing = calculateEarningsPerWash(ammountOfWashedTaxis, taxiWashingCost);
let moneyGeneratedByBusWashing = calculateEarningsPerWash(ammountOfWashedBuses, busWashingCost);
let moneyGeneratedByParticularWashing = calculateEarningsPerWash(ammountOfWashedParticular, particularWashingCost);
let moneyGeneratedByBikesWashing = calculateEarningsPerWash(ammountOfWashedBikes, bikeWashingCost);
//Total money generated
let totalMoneyGenerated = (moneyGeneratedByTaxiWashing + moneyGeneratedByBusWashing + moneyGeneratedByParticularWashing + moneyGeneratedByBikesWashing);


//INFO ON SCREEN
print(`<h2>LAVADERO S.A.S</h2>`);
print(`<strong>VEHICULOS LAVADOS</strong>`);
print(`Taxis lavados: ${ammountOfWashedTaxis}`);
print(`Buses lavados: ${ammountOfWashedBuses}`);
print(`Particulares lavados: ${ammountOfWashedParticular}`);
print(`Motos lavadas: ${ammountOfWashedBikes}`);
print(`<strong>Total vehiculos lavados durante la jornada:</strong> ${totalVehiclesWashed}`);
lineBreak();
print(`<strong>DINERO GENERADO</strong>`);
print(`Dinero generado por lavado de TAXIS: ${moneyGeneratedByTaxiWashing}$`);
print(`Dinero generado por lavado de BUSES: ${moneyGeneratedByBusWashing}$`);
print(`Dinero generado por lavado de CARROS PARTICULARES: ${moneyGeneratedByParticularWashing}$`);
print(`Dinero generado por lavado de MOTOS: ${moneyGeneratedByBikesWashing}$`);
print(`<strong>Total de dinero generado durante la jornada:</strong> ${totalMoneyGenerated}$`);



